name: Code Checks

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
  release:
    types: [published]

jobs:
  pre-commit:
    name: "Run pre-commit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
